  
# DESCRIPTION: GitLab CI/CD for libRetro (NOT FOR GitLab-proper)

##############################################################################
################################# BOILERPLATE ################################
##############################################################################

# Core definitions
.core-defs:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    JNI_PATH: libretro
    CORENAME: dosbox_core
    MAKEFILE_PATH: libretro
    MAKEFILE: Makefile.libretro

# Inclusion templates, required for the build to work
include:
  ################################## DESKTOPS ################################
  # Windows 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/windows-x64-mingw.yml'
    
  # Windows 32-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/windows-i686-mingw.yml'

  # Linux 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/linux-x64.yml'
    
  ################################## CELLULAR ################################
  # Android
  - project: 'libretro-infrastructure/ci-templates'
    file: '/android-jni.yml'

  ################################## CONSOLES ################################
  # Nintendo Switch
  - project: 'libretro-infrastructure/ci-templates'
    file: '/libnx-static.yml'

# Stages for building
stages:
  - build-prepare
  - build-shared
  - build-static

##############################################################################
#################################### STAGES ##################################
##############################################################################
#
################################### DESKTOPS #################################
# Windows 64-bit
libretro-build-windows-x64:
  extends:
    - .libretro-windows-x64-mingw-make-default
    - .core-defs
  variables:
    CC: gcc
    CXX: g++
    CMAKE_GENERATOR: Ninja
    platform: win
    TARGET_TRIPLET: x86_64-w64-mingw32.static
    BUNDLED_AUDIO_CODECS: 0
    BUNDLED_GLIB: 0
    BUNDLED_LIBSNDFILE: 0
    BUNDLED_SDL: 0
    STATIC_LIBCXX: 0
    WITH_BASSMIDI: 1
    WITH_DYNAREC: x86_64
    WITH_FLUIDSYNTH: 1
    WITH_VOODOO: 1
  script:
    - make -C ${MAKEFILE_PATH} -f ${MAKEFILE} deps
    - make -C ${MAKEFILE_PATH} -f ${MAKEFILE} -j${NUMPROC}
    - x86_64-w64-mingw32.static-strip ${MAKEFILE_PATH}/${CORENAME}_libretro.dll

# Windows 32-bit
libretro-build-windows-i686:
  extends:
    - .libretro-windows-i686-mingw-make-default
    - .core-defs
  variables:
    CC: gcc
    CXX: g++
    CMAKE_GENERATOR: Ninja
    platform: win
    TARGET_TRIPLET: i686-w64-mingw32.static
    BUNDLED_AUDIO_CODECS: 0
    BUNDLED_GLIB: 0
    BUNDLED_LIBSNDFILE: 0
    BUNDLED_SDL: 0
    STATIC_LIBCXX: 0
    WITH_BASSMIDI: 1
    WITH_DYNAREC: x86
    WITH_FLUIDSYNTH: 1
    WITH_VOODOO: 1
  script:
    - make -C ${MAKEFILE_PATH} -f ${MAKEFILE} deps
    - make -C ${MAKEFILE_PATH} -f ${MAKEFILE} -j${NUMPROC}
    - i686-w64-mingw32.static-strip ${MAKEFILE_PATH}/${CORENAME}_libretro.dll

# Linux 64-bit
libretro-build-linux-x64:
  extends:
    - .libretro-linux-x64-make-default
    - .core-defs
  variables:
    CC: gcc-9
    CXX: g++-9
    platform: unix
    BUNDLED_AUDIO_CODECS: 1
    BUNDLED_GLIB: 1
    BUNDLED_LIBSNDFILE: 1
    BUNDLED_SDL: 1
    CMAKE_GENERATOR: Ninja
    STATIC_LIBCXX: 1
    WITH_BASSMIDI: 1
    WITH_DYNAREC: x86_64
    WITH_FLUIDSYNTH: 1
    WITH_VOODOO: 1
  image: $CI_SERVER_HOST:5050/libretro-infrastructure/libretro-build-amd64-ubuntu:dosbox-core
  script:
    - make -C ${MAKEFILE_PATH} -f ${MAKEFILE} deps
    - make -C ${MAKEFILE_PATH} -f ${MAKEFILE} -j${NUMPROC}
    - strip ${MAKEFILE_PATH}/${CORENAME}_libretro.so

################################### CELLULAR #################################
# Android ARMv7a
android-armeabi-v7a:
  extends:
    - .libretro-android-jni-armeabi-v7a
    - .core-defs
  variables:
    CMAKE: cmake
    CMAKE_BUILD_TYPE: Release
  script:
    - DEPS_BIN_DIR="$PWD/$MAKEFILE_PATH/deps_bin/$ANDROID_ABI"
      EXTRA_CMAKE_FLAGS="-DANDROID_PLATFORM=android-24 -DCMAKE_TOOLCHAIN_FILE=${NDK_ROOT}/build/cmake/android.toolchain.cmake -DANDROID_STL=c++_static -DANDROID_ABI=${ANDROID_ABI}"
      make -C ${MAKEFILE_PATH} -f deps/munt.makefile
    - $NDK_ROOT/ndk-build --no-print-directory -j$NUMPROC -C $JNI_PATH/jni $PLATFORM_ARGS
    - mv $JNI_PATH/libs/$ANDROID_ABI/libretro.so $LIBNAME
    - if [ $STRIP_CORE_LIB -eq 1 ]; then $NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip $LIBNAME; fi

# Android ARMv8a
android-arm64-v8a:
  extends:
    - .libretro-android-jni-arm64-v8a
    - .core-defs
  variables:
    CMAKE: cmake
    CMAKE_BUILD_TYPE: Release
  script:
    - DEPS_BIN_DIR="$PWD/$MAKEFILE_PATH/deps_bin/$ANDROID_ABI"
      EXTRA_CMAKE_FLAGS="-DANDROID_PLATFORM=android-24 -DCMAKE_TOOLCHAIN_FILE=${NDK_ROOT}/build/cmake/android.toolchain.cmake -DANDROID_STL=c++_static -DANDROID_ABI=${ANDROID_ABI}"
      make -C ${MAKEFILE_PATH} -f deps/munt.makefile
    - $NDK_ROOT/ndk-build --no-print-directory -j$NUMPROC -C $JNI_PATH/jni $PLATFORM_ARGS
    - mv $JNI_PATH/libs/$ANDROID_ABI/libretro.so $LIBNAME
    - if [ $STRIP_CORE_LIB -eq 1 ]; then $NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip $LIBNAME; fi

# Android 64-bit x86
android-x86_64:
  extends:
    - .libretro-android-jni-x86_64
    - .core-defs
  variables:
    CMAKE: cmake
    CMAKE_BUILD_TYPE: Release
  script:
    - DEPS_BIN_DIR="$PWD/$MAKEFILE_PATH/deps_bin/$ANDROID_ABI"
      EXTRA_CMAKE_FLAGS="-DANDROID_PLATFORM=android-24 -DCMAKE_TOOLCHAIN_FILE=${NDK_ROOT}/build/cmake/android.toolchain.cmake -DANDROID_STL=c++_static -DANDROID_ABI=${ANDROID_ABI}"
      make -C ${MAKEFILE_PATH} -f deps/munt.makefile
    - $NDK_ROOT/ndk-build --no-print-directory -j$NUMPROC -C $JNI_PATH/jni $PLATFORM_ARGS
    - mv $JNI_PATH/libs/$ANDROID_ABI/libretro.so $LIBNAME
    - if [ $STRIP_CORE_LIB -eq 1 ]; then $NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip $LIBNAME; fi

# Android 32-bit x86
android-x86:
  extends:
    - .libretro-android-jni-x86
    - .core-defs
  variables:
    CMAKE: cmake
    CMAKE_BUILD_TYPE: Release
  script:
    - DEPS_BIN_DIR="$PWD/$MAKEFILE_PATH/deps_bin/$ANDROID_ABI"
      EXTRA_CMAKE_FLAGS="-DANDROID_PLATFORM=android-24 -DCMAKE_TOOLCHAIN_FILE=${NDK_ROOT}/build/cmake/android.toolchain.cmake -DANDROID_STL=c++_static -DANDROID_ABI=${ANDROID_ABI}"
      make -C ${MAKEFILE_PATH} -f deps/munt.makefile
    - $NDK_ROOT/ndk-build --no-print-directory -j$NUMPROC -C $JNI_PATH/jni $PLATFORM_ARGS
    - mv $JNI_PATH/libs/$ANDROID_ABI/libretro.so $LIBNAME
    - if [ $STRIP_CORE_LIB -eq 1 ]; then $NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip $LIBNAME; fi

################################### CONSOLES #################################
# Nintendo Switch
libretro-build-libnx-aarch64:
  extends:
    - .libretro-libnx-static-retroarch-master
    - .core-defs
  variables:
    CMAKE_GENERATOR: 'Unix Makefiles'
